name: Java CI

on:
  push:
    branches-ignore:
    - gh-pages

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java: [ '11', '17', '21' ]
        maven: [ '3.8.8', '3.9.6' ]

    steps:
    - uses: actions/checkout@v3
    - name: Setup Maven Action
      uses: s4u/setup-maven-action@v1.11.0
      with:
        maven-version: ${{ matrix.maven }}
        java-version: ${{ matrix.java }}
        java-distribution: 'temurin'
    - name: Build with Maven
      run: mvn --batch-mode verify