name: Publish to Maven Central
on:
  release:
    types: [ created ]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: List keys
      run: gpg --list-secret-keys --keyid-format LONG

    - name: Set up Apache Maven Central
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'
        server-id: ossrh
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD
        gpg-private-key: ${{ secrets.OSSRH_GPG_SECRET_KEY }}
        gpg-passphrase: GPG_PASSPHRASE

    - name: Display settings.xml
      run: cat /home/runner/.m2/settings.xml

    - name: Test GPG_PASSPHRASE
      run: echo "GPG_PASSPHRASE=${GPG_PASSPHRASE}"
      env:
        GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

    - name: Test usage
      run: echo "${GPG_PASSPHRASE}" | gpg --batch --passphrase-fd 0 --pinentry-mode loopback --local-user chas@honton.org -as /home/runner/.m2/settings.xml
      env:
        GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

    - name: Publish to Apache Maven Central
      run: mvn -P release deploy site-deploy -X
      env:
        MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
