name: Publish to Maven Central

on:
  release:
    branches-ignore:
    - gh-pages
    types:
    - created

jobs:
  central:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Apache Maven Central
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'
        server-id: ossrh
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD
        gpg-private-key: ${{ secrets.OSSRH_GPG_SECRET_KEY }}
        gpg-passphrase: GPG_PASSPHRASE

    - name: Publish to Apache Maven Central
      run: mvn -P release deploy
      env:
        MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
        GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
